#!/bin/bash
#
# USAGE: dic [-w] 'some phrase'
#
# -n    do not use `less'
#

set -u

tmp="/tmp/.dic_tmp.$$"
flgLess=1

a="$1"
if [ "$a" = '-n' ]; then
	flgLess=0
	shift
fi

w="$1"

cleanup() {
	rm -f "$tmp"
	echo
	exit
}

trap cleanup SIGTERM 
trap cleanup SIGINT 

dict "$w" > "$tmp"
if [ $? -ne 0 ]; then
	#wikidic -n "$w" > "$tmp"
	oxdic -n "$w" > "$tmp"
fi

if [ $flgLess -ne 0 ]; then
	cat "$tmp" | less
else
	cat "$tmp"
fi

cleanup
