#!/usr/bin/python3

import sys, os
from pathlib import Path
appPath = Path(__file__).parent.absolute()
sys.path = [str(appPath)] + sys.path

from DictionaryAppMU import DictionaryAppMU

dapp = DictionaryAppMU(clArgs=sys.argv)
dapp.run()
