#!/usr/bin/python3

import sys, os
from pathlib import Path
appPath = Path(__file__).parent.absolute()
sys.path = [str(appPath), str(appPath / '..')] + sys.path

from EasyPipe import Pipe
cmd = "dict father".split()
p = Pipe(cmd)
assert p.status == 0
